### ISSUE TITLE
gMusic Opera Extension not working

### ISSUE THREAD

**Issue by bnleez** [annoyingmouse/gMusic#3]
Installed gMusic extention and it remains grayed out.  It's a no-go.

**Comment by annoyingmouse** [comment]
Hi @bnleez, I've just re-installed Opera and re-installed this extension and visited [https://play.google.com/music/listen](https://play.google.com/music/listen) and everything seems to be working. I had to restart Opera in order for the extension to work but it requires Google Music to be open. It merely acts as a remote control from the taskbar - the site still needs to be open. If you had it open please make sure you restart Opera. Let me know how you get on.

**Comment by bnleez** [comment]
It´s working now, not sure what happened.  Thanks for following up!

Benjamin

**Comment by annoyingmouse** [comment]
Nice one @bnleez, glad everything's sorted. I'll close this issue now.
